packages:
  - apps/*
  - packages/**
  - tooling/*

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - supabase

overrides:
  react-is: "19.0.0"
  basic-ftp: "^5.2.0"
  handlebars: "^4.7.9"
  tmp: "0.2.6"
  picomatch: "^4.0.4"